### PR TITLE
load/save state support

### PR DESCRIPTION
**Pull request by antorsae**
Minimal load/save state support. Tested saving/loading and rewind. #14

### CODE REVIEW

**Comment by fr500** [comment]
am I right saying that this ends up writing a mem0 file and destroying it later?

**Comment by fr500** [comment]
What should happen instead is that `boardSaveState` should be reimplemented so it uses a memory buffer instead of writing a zip file.

**Comment by twinaphex** [comment]
retro_serialize should not be file I/O based yeah but should work entirely in-memory.

**Comment by antorsae** [comment]
It does not write a file to disk. The `zip...` functions in `ziphelper.c` check if the filename starts with `mem` and if so they use a structure `MemFile` instead of file i/o to keep the rest of the code as is. If this how the states and rewind functionality works inside the original bluemsx emulator.

The hacky part of the code as I submitted is:
- it assumes savestates are going to be 2 Mbytes or less. I tested a lot of games and proved true.
- for efficiency yes, the original bluemsx code builds savestates incrementally in non-contiguous memory so I collate everything to send it to the retro frontend, which is some 2 Mbyte of memcpy. But I did it this way to minimize changes to the original bluemsx code.

**Comment by fr500** [comment]
ah ok, I retract myself then.

**Comment by twinaphex** [comment]
sorry for merging this so late. So, here goes.

**Comment by twinaphex** [comment]
Hi there @antorsae,

I merged the PR but now it won't build anymore on MSVC 2005 -

cl.exe -c -FoSrc/Libretro/Emulator.o Src/Libretro/Emulator.c -DGIT_VERSION=\"" 77a7910"\" -D_CRT_SECURE_NO_DEPRECATE -O2   -D__LIBRETRO__ -DSINGLE_THREADED -DVIDEO_COLOR_TYPE_RGB565 -DZ80_CUSTOM_CONFIGURATION -DNO_FRAMEBUFFER -DHAVE_WIN32_MSX_MANAGER -w  -I. -I./libretro-common/include -I./Src/Arch -I./Src/Bios -I./Src/Board -I./Src/BuildInfo -I./Src/Common -I./Src/Debugger -I./Src/Emulator -I./Src/IoDevice -I./Src/Language -I./Src/Media -I./Src/Memory -I./Src/Resources -I./Src/SoundChips -I./Src/TinyXML -I./Src/Unzip -I./Src/Utils -I./Src/VideoChips -I./Src/VideoRender -I./Src/Z80 -I./Src/Input -I./Src/Libretro -I./deps/zlib
libretro.c(1296) : error C2059: syntax error : '{'

Can you please fix this?

Also, for future reference, C files have to compile as C89 so that older MSVC versions can still compile them.

**Comment by twinaphex** [comment]
I fixed it for now like this -

https://github.com/libretro/blueMSX-libretro/commit/c7c7f01b556ed353deb20402b404b9151b241b0f

**Pull request merged**
